---
- name: Copiant fitxers de configuració NFS
  copy: src=files/exports dest=/etc/exports

- name: Copiant fitxers de configuració NFS
  copy: src=files/nfs-kernel-server dest=/etc/default/nfs-kernel-server

- file:
        path: /etc/exports
        owner: root
        group: root
        mode: 0644

- name: Activant servei NFS
  service: name=nfs-kernel-server state=started enabled=yes
  notify: restart nfs-server
