---
- name: Verificant unitats compartides
  file:
        path: /srv/exports
        state: directory
        owner: root
        group: root
        mode: 00775

- name: Verificant unitat P
  file:
        path: /srv/exports/P
        state: directory
        owner: root
        group: root
        mode: 06770

- name: Verificant unitats S
  file:
        path: /srv/exports/S
        state: directory
        owner: root
        group: root
        mode: 06775

- name: Verificant unitats T
  file:
        path: /srv/exports/T
        state: directory
        owner: root
        group: root
        mode: 00777

- name: Verificant unitats M
  file:
        path: /srv/exports/M
        state: directory
        owner: root
        group: root
        mode: 06770

- name: Verificant unitats G
  file:
        path: /srv/exports/G
        state: directory
        owner: root
        group: root
        mode: 06770

- name: Verificant Paperera
  file:
        path: /srv/exports/Paperera
        state: directory
        owner: root
        group: root
        mode: 02775

- name: Verificant Paperera P
  file:
        path: /srv/exports/Paperera/Paperera_Unitat_P
        state: directory
        owner: root
        group: root
        mode: 00770

#- name: Verificant Paperera S
#  file:
#        path: /srv/exports/Paperera/Paperera_Unitat_S
#        state: directory
#        owner: root
#        group: root
#        mode: 00644

- name: Verificant Paperera T
  file:
        path: /srv/exports/Paperera/Paperera_Unitat_T
        state: directory
        owner: root
        group: root
        mode: 00775

- name: Verificant Paperera M
  file:
        path: /srv/exports/Paperera/Paperera_Unitat_M
        state: directory
        owner: root
        group: root
        mode: 00770

- name: Verificant Paperera G
  file:
        path: /srv/exports/Paperera/Paperera_Unitat_G
        state: directory
        owner: root
        group: root
        mode: 00770

- name: Verificant Quarantine
  file:
        path: /var/quarantine
        state: directory
        owner: clamav
        group: root
        mode: 00770

- name: Verificant unitat Arxius
  file:
        path: /srv/exports/arxius
        state: directory
        owner: lnadmin 
        group: root
        mode: 06770

- name: Verificant unitat CloudPrint
  file:
        path: /srv/exports/cloudprint
        state: directory
        owner: root
        group: root
        mode: 06770

- name: Verificant unitats Maquetes
  file:
        path: /srv/exports/maquetes
        state: directory
        owner: root
        group: root
        mode: 06770

- name: Verificant unitats FOG 
  file:
        path: /srv/fog/images
        state: directory
        owner: 1000
        group: root 
        mode: 00770

- name: Verificant unitats FOG
  file:
        path: /srv/fog/images/dev
        state: directory
        owner: 1000
        group: root
        mode: 00770

- name: Unitats dades Docker
  file:
        path: /srv/app
        state: directory
        owner: root
        group: root
        mode: 00770
